Document: iroffer-dinoex
Title: Debian iroffer-dinoex Manual
Author: <insert document author here>
Abstract: This manual describes what iroffer-dinoex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iroffer-dinoex/iroffer-dinoex.sgml.gz

Format: postscript
Files: /usr/share/doc/iroffer-dinoex/iroffer-dinoex.ps.gz

Format: text
Files: /usr/share/doc/iroffer-dinoex/iroffer-dinoex.text.gz

Format: HTML
Index: /usr/share/doc/iroffer-dinoex/html/index.html
Files: /usr/share/doc/iroffer-dinoex/html/*.html
